### ISSUE TITLE
clientJS/test throws Exception

### ISSUE THREAD

**Issue by fthomas** [fthomas/kartograffel#4]
@btre Beim Testen des Clients fliegt folgende Exception:
```
sbt:kartograffel> clientJS/test
[error] module.js:328
[error]     throw err;
[error]     ^
[error] Error: Cannot find module 'react'
[error]     at Function.Module._resolveFilename (module.js:326:15)
[error]     at Function.Module._load (module.js:277:25)
[error]     at Module.require (module.js:354:17)
[error]     at require (internal/module.js:12:17)
[error]     at /tmp/1504474556449-0/react-dom.js:8:24
[error]     at Object.<anonymous> (/tmp/1504474556449-0/react-dom.js:31:3)
[error]     at Module._compile (module.js:410:26)
[error]     at Object.Module._extensions..js (module.js:417:10)
[error]     at Module.load (module.js:344:32)
[error]     at Function.Module._load (module.js:301:12)
[error] org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
```
Fehlt hier noch eine Library in `jsDependencies`?

**Comment by fthomas** [comment]
Mit diesem Diff läuft der Test:
```diff
--- a/build.sbt
+++ b/build.sbt
@@ -52,13 +52,13 @@ lazy val client = crossProject(JSPlatform)
     jsDependencies ++= Seq(
       "org.webjars" % "jquery" % webjarJqueryVersion / s"$webjarJqueryVersion/jquery.js",
       "org.webjars.bower" % "react" % webjarReactVersion
-        / "react-with-addons.js"
+        / "react.js"
         minified "react-with-addons.min.js"
         commonJSName "React",
       "org.webjars.bower" % "react" % webjarReactVersion
         / "react-dom.js"
         minified "react-dom.min.js"
-        dependsOn "react-with-addons.js"
+        dependsOn "react.js"
         commonJSName "ReactDOM"
     ),
     scalaJSUseMainModuleInitializer := true
```
